# Generated by Django 2.2.4 on 2019-08-15 15:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absense_type', models.CharField(choices=[('Vacaciones', 'Cargo a Vacaciones'), ('Enfermedad', 'Enfermedad'), ('Compensacion', 'Compensación'), ('Calamidad', 'Calamidad'), ('Certificado', 'Presentar Certificado')], default='Vacaciones', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
    ]
